# Generated by Django 5.0.4 on 2024-04-13 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentmanagement', '0002_alter_equipment_serial_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='return_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expected_return_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='checkout_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Signed Out', 'signed_out')], max_length=20),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagement.equipment')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagement.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='equipment',
            field=models.ManyToManyField(through='equipmentmanagement.CartItem', to='equipmentmanagement.equipment'),
        ),
    ]
