# Generated by Django 5.0.4 on 2024-04-14 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentmanagement', '0003_remove_transaction_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='equipmentmanagement.cart'),
        ),
    ]
