# Generated by Django 5.0.4 on 2024-04-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentmanagement', '0004_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='checkout_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('signed_out', 'Signed Out'), ('returned', 'Returned')], default='signed_out', max_length=20),
        ),
    ]
